# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pxg/PetPS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pxg/PetPS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pxg/PetPS/CMakeFiles /home/pxg/PetPS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pxg/PetPS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named mayfly

# Build rule for target.
mayfly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mayfly
.PHONY : mayfly

# fast build rule for target.
mayfly/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/mayfly.dir/build.make third_party/Mayfly-main/CMakeFiles/mayfly.dir/build
.PHONY : mayfly/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/client.dir/build.make third_party/Mayfly-main/CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named client_cli

# Build rule for target.
client_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_cli
.PHONY : client_cli

# fast build rule for target.
client_cli/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/client_cli.dir/build.make third_party/Mayfly-main/CMakeFiles/client_cli.dir/build
.PHONY : client_cli/fast

#=============================================================================
# Target rules for targets named mayfly_client_rpc

# Build rule for target.
mayfly_client_rpc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mayfly_client_rpc
.PHONY : mayfly_client_rpc

# fast build rule for target.
mayfly_client_rpc/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/mayfly_client_rpc.dir/build.make third_party/Mayfly-main/CMakeFiles/mayfly_client_rpc.dir/build
.PHONY : mayfly_client_rpc/fast

#=============================================================================
# Target rules for targets named mayfly_server

# Build rule for target.
mayfly_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mayfly_server
.PHONY : mayfly_server

# fast build rule for target.
mayfly_server/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/mayfly_server.dir/build.make third_party/Mayfly-main/CMakeFiles/mayfly_server.dir/build
.PHONY : mayfly_server/fast

#=============================================================================
# Target rules for targets named outbound

# Build rule for target.
outbound: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 outbound
.PHONY : outbound

# fast build rule for target.
outbound/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/outbound.dir/build.make third_party/Mayfly-main/CMakeFiles/outbound.dir/build
.PHONY : outbound/fast

#=============================================================================
# Target rules for targets named rpc_test

# Build rule for target.
rpc_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rpc_test
.PHONY : rpc_test

# fast build rule for target.
rpc_test/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Mayfly-main/CMakeFiles/rpc_test.dir/build.make third_party/Mayfly-main/CMakeFiles/rpc_test.dir/build
.PHONY : rpc_test/fast

#=============================================================================
# Target rules for targets named PMDK

# Build rule for target.
PMDK: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PMDK
.PHONY : PMDK

# fast build rule for target.
PMDK/fast:
	$(MAKE) $(MAKESILENT) -f third_party/dash/CMakeFiles/PMDK.dir/build.make third_party/dash/CMakeFiles/PMDK.dir/build
.PHONY : PMDK/fast

#=============================================================================
# Target rules for targets named compile_pmdk

# Build rule for target.
compile_pmdk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_pmdk
.PHONY : compile_pmdk

# fast build rule for target.
compile_pmdk/fast:
	$(MAKE) $(MAKESILENT) -f third_party/dash/CMakeFiles/compile_pmdk.dir/build.make third_party/dash/CMakeFiles/compile_pmdk.dir/build
.PHONY : compile_pmdk/fast

#=============================================================================
# Target rules for targets named test_pmem

# Build rule for target.
test_pmem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_pmem
.PHONY : test_pmem

# fast build rule for target.
test_pmem/fast:
	$(MAKE) $(MAKESILENT) -f third_party/dash/CMakeFiles/test_pmem.dir/build.make third_party/dash/CMakeFiles/test_pmem.dir/build
.PHONY : test_pmem/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f third_party/dash/CMakeFiles/example.dir/build.make third_party/dash/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named PMHashPCLHT

# Build rule for target.
PMHashPCLHT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PMHashPCLHT
.PHONY : PMHashPCLHT

# fast build rule for target.
PMHashPCLHT/fast:
	$(MAKE) $(MAKESILENT) -f third_party/HashEvaluation-for-petps/CMakeFiles/PMHashPCLHT.dir/build.make third_party/HashEvaluation-for-petps/CMakeFiles/PMHashPCLHT.dir/build
.PHONY : PMHashPCLHT/fast

#=============================================================================
# Target rules for targets named PMHashLevel

# Build rule for target.
PMHashLevel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PMHashLevel
.PHONY : PMHashLevel

# fast build rule for target.
PMHashLevel/fast:
	$(MAKE) $(MAKESILENT) -f third_party/HashEvaluation-for-petps/CMakeFiles/PMHashLevel.dir/build.make third_party/HashEvaluation-for-petps/CMakeFiles/PMHashLevel.dir/build
.PHONY : PMHashLevel/fast

#=============================================================================
# Target rules for targets named PMHashClevel

# Build rule for target.
PMHashClevel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PMHashClevel
.PHONY : PMHashClevel

# fast build rule for target.
PMHashClevel/fast:
	$(MAKE) $(MAKESILENT) -f third_party/HashEvaluation-for-petps/CMakeFiles/PMHashClevel.dir/build.make third_party/HashEvaluation-for-petps/CMakeFiles/PMHashClevel.dir/build
.PHONY : PMHashClevel/fast

#=============================================================================
# Target rules for targets named PMHashCCEHVM

# Build rule for target.
PMHashCCEHVM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PMHashCCEHVM
.PHONY : PMHashCCEHVM

# fast build rule for target.
PMHashCCEHVM/fast:
	$(MAKE) $(MAKESILENT) -f third_party/HashEvaluation-for-petps/CMakeFiles/PMHashCCEHVM.dir/build.make third_party/HashEvaluation-for-petps/CMakeFiles/PMHashCCEHVM.dir/build
.PHONY : PMHashCCEHVM/fast

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) $(MAKESILENT) -f src/base/CMakeFiles/base.dir/build.make src/base/CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named base_memory

# Build rule for target.
base_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 base_memory
.PHONY : base_memory

# fast build rule for target.
base_memory/fast:
	$(MAKE) $(MAKESILENT) -f src/memory/CMakeFiles/base_memory.dir/build.make src/memory/CMakeFiles/base_memory.dir/build
.PHONY : base_memory/fast

#=============================================================================
# Target rules for targets named pm_command

# Build rule for target.
pm_command: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pm_command
.PHONY : pm_command

# fast build rule for target.
pm_command/fast:
	$(MAKE) $(MAKESILENT) -f src/memory/CMakeFiles/pm_command.dir/build.make src/memory/CMakeFiles/pm_command.dir/build
.PHONY : pm_command/fast

#=============================================================================
# Target rules for targets named pet_kv

# Build rule for target.
pet_kv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pet_kv
.PHONY : pet_kv

# fast build rule for target.
pet_kv/fast:
	$(MAKE) $(MAKESILENT) -f src/pet_kv/CMakeFiles/pet_kv.dir/build.make src/pet_kv/CMakeFiles/pet_kv.dir/build
.PHONY : pet_kv/fast

#=============================================================================
# Target rules for targets named PiBenchPetHash

# Build rule for target.
PiBenchPetHash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PiBenchPetHash
.PHONY : PiBenchPetHash

# fast build rule for target.
PiBenchPetHash/fast:
	$(MAKE) $(MAKESILENT) -f src/pet_kv/CMakeFiles/PiBenchPetHash.dir/build.make src/pet_kv/CMakeFiles/PiBenchPetHash.dir/build
.PHONY : PiBenchPetHash/fast

#=============================================================================
# Target rules for targets named PiBenchDash

# Build rule for target.
PiBenchDash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PiBenchDash
.PHONY : PiBenchDash

# fast build rule for target.
PiBenchDash/fast:
	$(MAKE) $(MAKESILENT) -f src/pet_kv/CMakeFiles/PiBenchDash.dir/build.make src/pet_kv/CMakeFiles/PiBenchDash.dir/build
.PHONY : PiBenchDash/fast

#=============================================================================
# Target rules for targets named perf_kv_engine

# Build rule for target.
perf_kv_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf_kv_engine
.PHONY : perf_kv_engine

# fast build rule for target.
perf_kv_engine/fast:
	$(MAKE) $(MAKESILENT) -f src/kv_engine/CMakeFiles/perf_kv_engine.dir/build.make src/kv_engine/CMakeFiles/perf_kv_engine.dir/build
.PHONY : perf_kv_engine/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f src/kv_engine/CMakeFiles/bench.dir/build.make src/kv_engine/CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named wq_ps_client

# Build rule for target.
wq_ps_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wq_ps_client
.PHONY : wq_ps_client

# fast build rule for target.
wq_ps_client/fast:
	$(MAKE) $(MAKESILENT) -f src/ps/CMakeFiles/wq_ps_client.dir/build.make src/ps/CMakeFiles/wq_ps_client.dir/build
.PHONY : wq_ps_client/fast

#=============================================================================
# Target rules for targets named petps_server

# Build rule for target.
petps_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 petps_server
.PHONY : petps_server

# fast build rule for target.
petps_server/fast:
	$(MAKE) $(MAKESILENT) -f src/ps/CMakeFiles/petps_server.dir/build.make src/ps/CMakeFiles/petps_server.dir/build
.PHONY : petps_server/fast

#=============================================================================
# Target rules for targets named perf_sgl

# Build rule for target.
perf_sgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf_sgl
.PHONY : perf_sgl

# fast build rule for target.
perf_sgl/fast:
	$(MAKE) $(MAKESILENT) -f src/benchmark/CMakeFiles/perf_sgl.dir/build.make src/benchmark/CMakeFiles/perf_sgl.dir/build
.PHONY : perf_sgl/fast

#=============================================================================
# Target rules for targets named dataset_wordcount_helper

# Build rule for target.
dataset_wordcount_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dataset_wordcount_helper
.PHONY : dataset_wordcount_helper

# fast build rule for target.
dataset_wordcount_helper/fast:
	$(MAKE) $(MAKESILENT) -f src/benchmark/CMakeFiles/dataset_wordcount_helper.dir/build.make src/benchmark/CMakeFiles/dataset_wordcount_helper.dir/build
.PHONY : dataset_wordcount_helper/fast

#=============================================================================
# Target rules for targets named dataset_renumber_id_helper

# Build rule for target.
dataset_renumber_id_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dataset_renumber_id_helper
.PHONY : dataset_renumber_id_helper

# fast build rule for target.
dataset_renumber_id_helper/fast:
	$(MAKE) $(MAKESILENT) -f src/benchmark/CMakeFiles/dataset_renumber_id_helper.dir/build.make src/benchmark/CMakeFiles/dataset_renumber_id_helper.dir/build
.PHONY : dataset_renumber_id_helper/fast

#=============================================================================
# Target rules for targets named benchmark_client

# Build rule for target.
benchmark_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_client
.PHONY : benchmark_client

# fast build rule for target.
benchmark_client/fast:
	$(MAKE) $(MAKESILENT) -f src/benchmark/CMakeFiles/benchmark_client.dir/build.make src/benchmark/CMakeFiles/benchmark_client.dir/build
.PHONY : benchmark_client/fast

#=============================================================================
# Target rules for targets named persist_memorypool_test

# Build rule for target.
persist_memorypool_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 persist_memorypool_test
.PHONY : persist_memorypool_test

# fast build rule for target.
persist_memorypool_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/persist_memorypool_test.dir/build.make test/CMakeFiles/persist_memorypool_test.dir/build
.PHONY : persist_memorypool_test/fast

#=============================================================================
# Target rules for targets named persist_pet_hash_test

# Build rule for target.
persist_pet_hash_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 persist_pet_hash_test
.PHONY : persist_pet_hash_test

# fast build rule for target.
persist_pet_hash_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/persist_pet_hash_test.dir/build.make test/CMakeFiles/persist_pet_hash_test.dir/build
.PHONY : persist_pet_hash_test/fast

#=============================================================================
# Target rules for targets named petkv_multithread_test

# Build rule for target.
petkv_multithread_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 petkv_multithread_test
.PHONY : petkv_multithread_test

# fast build rule for target.
petkv_multithread_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/petkv_multithread_test.dir/build.make test/CMakeFiles/petkv_multithread_test.dir/build
.PHONY : petkv_multithread_test/fast

#=============================================================================
# Target rules for targets named kv_engine_test

# Build rule for target.
kv_engine_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kv_engine_test
.PHONY : kv_engine_test

# fast build rule for target.
kv_engine_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/kv_engine_test.dir/build.make test/CMakeFiles/kv_engine_test.dir/build
.PHONY : kv_engine_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... PMDK"
	@echo "... compile_pmdk"
	@echo "... PMHashCCEHVM"
	@echo "... PMHashClevel"
	@echo "... PMHashLevel"
	@echo "... PMHashPCLHT"
	@echo "... PiBenchDash"
	@echo "... PiBenchPetHash"
	@echo "... base"
	@echo "... base_memory"
	@echo "... bench"
	@echo "... benchmark_client"
	@echo "... client"
	@echo "... client_cli"
	@echo "... dataset_renumber_id_helper"
	@echo "... dataset_wordcount_helper"
	@echo "... example"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... kv_engine_test"
	@echo "... mayfly"
	@echo "... mayfly_client_rpc"
	@echo "... mayfly_server"
	@echo "... outbound"
	@echo "... perf_kv_engine"
	@echo "... perf_sgl"
	@echo "... persist_memorypool_test"
	@echo "... persist_pet_hash_test"
	@echo "... pet_kv"
	@echo "... petkv_multithread_test"
	@echo "... petps_server"
	@echo "... pm_command"
	@echo "... rpc_test"
	@echo "... test_pmem"
	@echo "... wq_ps_client"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

